title: Sudeshna Mazumder
logo: /assets/img/logo.png
description: I am working professional with 6 years of experience in the Pharmacovigilance domain. Currently pursuing Masters in Data Science, I intend to master the concepts of data science to give the best results to companies.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
